parser: '@typescript-eslint/parser'
parserOptions:
  tsconfigRootDir: ./
  project: ./tsconfig.json
plugins:
  - '@typescript-eslint/eslint-plugin'
  - jsdoc
extends:
  - eslint:recommended
  - plugin:@typescript-eslint/eslint-recommended
  - plugin:@typescript-eslint/recommended
  - plugin:@typescript-eslint/recommended-requiring-type-checking
  - plugin:jsdoc/recommended
rules:
  eqeqeq:
    - error
    - smart
  no-undef: off
  # '@typescript-eslint/no-use-before-define': off
  '@typescript-eslint/explicit-function-return-type': off
  # '@typescript-eslint/explicit-function-return-type':
  #   - warn
  #   - allowExpressions: true
  #     allowHigherOrderFunctions: true
  '@typescript-eslint/no-explicit-any': off
  '@typescript-eslint/no-inferrable-types': off
  '@typescript-eslint/no-unused-vars':
    - warn
    - ignoreRestSiblings: true
  jsdoc/check-alignment: off
overrides:
  # TypeScript
  - files: '**/*.ts?(x)'
    rules:
      jsdoc/require-param-type: off
      jsdoc/require-returns-type: off
  # JS Files
  - files: '**/*.js?(x)'
    rules:
      '@typescript-eslint/no-var-requires': off
  # Test files
  # - files: '**/(*.)+test.[jt]sx'
  #   rules:
  #     '@typescript-eslint/no-non-null-assertion': off
settings:
  jsdoc:
    mode: typescript
